/*
 * generated by Xtext 2.25.0
 */
package org.example.domainmodel.tests

import com.google.inject.Inject
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.extensions.InjectionExtension
import org.eclipse.xtext.testing.util.ParseHelper
import org.example.domainmodel.domainmodel.Domainmodel
import org.junit.jupiter.api.Assertions
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.^extension.ExtendWith
import org.example.domainmodel.domainmodel.Entity
import org.eclipse.xtext.testing.validation.ValidationTestHelper
import org.example.domainmodel.domainmodel.DomainmodelPackage
import org.example.domainmodel.validation.DomainmodelValidator
import org.eclipse.xtext.xbase.testing.CompilationTestHelper

@ExtendWith(InjectionExtension)
@InjectWith(DomainmodelInjectorProvider)
class DomainmodelParsingTest {
	@Inject ParseHelper<Domainmodel> parseHelper
	@Inject ValidationTestHelper validationTestHelper
	
    @Test 
 	def void parseDomainmodel() {
     val model = parseHelper.parse(
         "entity MyEntity {
             parent: MyEntity
         }")
     val entity = model.elements.head as Entity
     Assertions.assertSame(entity, entity.features.head.type)
     }
     
  	@Test
	def testNameStartsWithCapitalWarning() {
     	val entity = parseHelper.parse(
         "entity myEntity {
             parent: myEntity
         }")
	     validationTestHelper.assertWarning(entity,
	         DomainmodelPackage.Literals.ENTITY,
	         DomainmodelValidator.INVALID_NAME,
	         "Name should start with a capital"
		     )
		     }
 
 	@Inject extension ParseHelper<Domainmodel>
	@Inject extension ValidationTestHelper
	     
     @Test
     def parseDomainmodelInjected() {
         "entity MyEntity {
         parent: MyEntity
         }".parse.assertNoIssues
     }
	     
     @Test
     def testNameStartsWithCapitalWarningInjected() {
         "entity myEntity {
             parent: myEntity
         }".parse.assertWarning(
             DomainmodelPackage.Literals.ENTITY,
             DomainmodelValidator.INVALID_NAME,
             "Name should start with a capital"
         )
     }
	     
	     
	@Inject extension CompilationTestHelper
	@Test def test() {
     '''
     datatype String
     
     package my.company.blog {
         entity Blog {
             title: String
         }
     }
 '''.assertCompilesTo(
 '''
         package my.company.blog;
         
         public class Blog {
             private String title;
             
             public String getTitle() {
                 return title;
             }
             
             public void setTitle(String title) {
                 this.title = title;
             }
         }
     '''
     )
     }
}
